version: 0.2

phases:
  install:
    runtime-versions:
      java:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - aws cp s3::team-c-p1-orm/target/orm-0.1.jar ~/.m2/repository/com/revature/orm/0.1/orm-0.1.jar
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/team-c-p1-webapp.jar